### ISSUE TITLE
Integration test failed for feature/es-2.0.0

### ISSUE THREAD

**Issue by minosniu** [englishtown/vertx-elasticsearch-service#26]
I checked the out the mint branch feature/es-2.0.0, and tried to "mvn integration-test". All 21 test cases failed and here's a typical message:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.englishtown.vertx.elasticsearch.integration.GuiceIntegrationTest
Starting test: GuiceIntegrationTest#test1Index 
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Address must be resolved but wasn't - InetSocketAddress#getAddress() returned null
  at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator.<init>(EnvElasticSearchConfigurator.java:24)
  while locating com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator
  while locating com.englishtown.vertx.elasticsearch.ElasticSearchConfigurator
    for parameter 1 at com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchService.<init>(DefaultElasticSearchService.java:57)
  at com.englishtown.vertx.elasticsearch.guice.ElasticSearchBinder.configure(ElasticSearchBinder.java:31)
  while locating com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchService
  while locating com.englishtown.vertx.elasticsearch.ElasticSearchService
    for parameter 0 at com.englishtown.vertx.elasticsearch.ElasticSearchServiceVerticle.<init>(ElasticSearchServiceVerticle.java:17)
  while locating com.englishtown.vertx.elasticsearch.ElasticSearchServiceVerticle
Caused by: java.lang.IllegalArgumentException: Address must be resolved but wasn't - InetSocketAddress#getAddress() returned null
        at org.elasticsearch.common.transport.InetSocketTransportAddress.<init>(InetSocketTransportAddress.java:61)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.initTransportAddresses(JsonElasticSearchConfigurator.java:73)
        at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator.initTransportAddresses(EnvElasticSearchConfigurator.java:59)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.init(JsonElasticSearchConfigurator.java:51)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.<init>(JsonElasticSearchConfigurator.java:40)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.<init>(JsonElasticSearchConfigurator.java:33)
        at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator.<init>(EnvElasticSearchConfigurator.java:24)
        at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator$$FastClassByGuice$$60e320e2.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at com.englishtown.vertx.guice.GuiceVerticleLoader.createRealVerticle(GuiceVerticleLoader.java:155)
        at com.englishtown.vertx.guice.GuiceVerticleLoader.createRealVerticle(GuiceVerticleLoader.java:115)
        at com.englishtown.vertx.guice.GuiceVerticleLoader.start(GuiceVerticleLoader.java:73)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$159(DeploymentManager.java:429)
        at io.vertx.core.impl.DeploymentManager$$Lambda$30/709865851.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
        at io.vertx.core.impl.ContextImpl$$Lambda$20/1237493613.run(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)

2) Error injecting constructor, java.lang.IllegalArgumentException: Address must be resolved but wasn't - InetSocketAddress#getAddress() returned null
  at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator.<init>(EnvElasticSearchConfigurator.java:24)
  while locating com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator
  while locating com.englishtown.vertx.elasticsearch.ElasticSearchConfigurator
    for parameter 1 at com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchService.<init>(DefaultElasticSearchService.java:57)
  at com.englishtown.vertx.elasticsearch.guice.ElasticSearchBinder.configure(ElasticSearchBinder.java:31)
  while locating com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchService
  while locating com.englishtown.vertx.elasticsearch.internal.InternalElasticSearchService
    for parameter 0 at com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchAdminService.<init>(DefaultElasticSearchAdminService.java:27)
  at com.englishtown.vertx.elasticsearch.guice.ElasticSearchBinder.configure(ElasticSearchBinder.java:32)
  while locating com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchAdminService
  while locating com.englishtown.vertx.elasticsearch.ElasticSearchAdminService
    for parameter 1 at com.englishtown.vertx.elasticsearch.ElasticSearchServiceVerticle.<init>(ElasticSearchServiceVerticle.java:17)
  while locating com.englishtown.vertx.elasticsearch.ElasticSearchServiceVerticle
Caused by: java.lang.IllegalArgumentException: Address must be resolved but wasn't - InetSocketAddress#getAddress() returned null
        at org.elasticsearch.common.transport.InetSocketTransportAddress.<init>(InetSocketTransportAddress.java:61)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.initTransportAddresses(JsonElasticSearchConfigurator.java:73)
        at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator.initTransportAddresses(EnvElasticSearchConfigurator.java:59)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.init(JsonElasticSearchConfigurator.java:51)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.<init>(JsonElasticSearchConfigurator.java:40)
        at com.englishtown.vertx.elasticsearch.impl.JsonElasticSearchConfigurator.<init>(JsonElasticSearchConfigurator.java:33)
        at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator.<init>(EnvElasticSearchConfigurator.java:24)
        at com.englishtown.vertx.elasticsearch.impl.EnvElasticSearchConfigurator$$FastClassByGuice$$60e320e2.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at com.englishtown.vertx.guice.GuiceVerticleLoader.createRealVerticle(GuiceVerticleLoader.java:155)
        at com.englishtown.vertx.guice.GuiceVerticleLoader.createRealVerticle(GuiceVerticleLoader.java:115)
        at com.englishtown.vertx.guice.GuiceVerticleLoader.start(GuiceVerticleLoader.java:73)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$159(DeploymentManager.java:429)
        at io.vertx.core.impl.DeploymentManager$$Lambda$30/709865851.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
        at io.vertx.core.impl.ContextImpl$$Lambda$20/1237493613.run(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)

**Comment by minosniu** [comment]
Just found that I overridden the DNS setup in my local machine. The integration-test is still failing but with different error messages. Closing this now.
