### ISSUE TITLE
Intergration test failed with "VertxException: thread blocked"

### ISSUE THREAD

**Issue by minosniu** [englishtown/vertx-elasticsearch-service#28]
Here's the failure message. No integration-test could pass.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.englishtown.vertx.elasticsearch.integration.IntegrationTest
Starting test: IntegrationTest#test1Index 
[Changeling] loaded [], sites [] 
Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 2620 ms, time limit is 2000 
Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 3624 ms, time limit is 2000 
Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 4627 ms, time limit is 2000 
Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 5630 ms, time limit is 2000 

......

**Comment by minosniu** [comment]
Do I need to power up an Elasticsearch instance to pass this integration test? If I have an ES running, the integration test will give me the following failure message:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.englishtown.vertx.elasticsearch.integration.IntegrationTest
Starting test: IntegrationTest#test1Index 
[Toxin] loaded [], sites [] 
[Toxin] node [#transport#-1][localhost][inet[localhost/127.0.0.1:9300]] not part of the cluster Cluster [elasticsearch], ignoring... 
[Toxin] node [#transport#-1][localhost][inet[localhost/127.0.0.1:9300]] not part of the cluster Cluster [elasticsearch], ignoring... 
[Toxin] failed to get node info for [#transport#-2][localhost][inet[dockerhost/180.168.41.175:9300]], disconnecting... 
org.elasticsearch.transport.NodeDisconnectedException: [][inet[dockerhost/180.168.41.175:9300]][cluster:monitor/nodes/info] disconnected

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
Unhandled exception 
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:305)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:200)
	at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
	at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:102)
	at org.elasticsearch.client.transport.TransportClient.index(TransportClient.java:340)
	at org.elasticsearch.action.index.IndexRequestBuilder.doExecute(IndexRequestBuilder.java:266)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchService.index(DefaultElasticSearchService.java:99)
	at com.englishtown.vertx.elasticsearch.ElasticSearchServiceVertxProxyHandler.handle(ElasticSearchServiceVertxProxyHandler.java:136)
	at com.englishtown.vertx.elasticsearch.ElasticSearchServiceVertxProxyHandler.handle(ElasticSearchServiceVertxProxyHandler.java:58)
	at io.vertx.core.eventbus.impl.EventBusImpl$HandlerRegistration.handleMessage(EventBusImpl.java:1121)
	at io.vertx.core.eventbus.impl.EventBusImpl$HandlerRegistration.handle(EventBusImpl.java:1115)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$doReceive$179(EventBusImpl.java:755)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

......

**Comment by adrianluisgonzalez** [comment]
I added a [BUILD_README.md](https://github.com/englishtown/vertx-elasticsearch-service/blob/develop/BUILD_README.md) to hopefully clear things up.

This describes the two new maven profiles for integration tests
* `localhost` (active by default)
* `dockerhost`

Does that help?

**Comment by minosniu** [comment]
Thanks, but other than test1Index, the rest of integration-tests are still failing with Thread blocked exceptions:

Running com.englishtown.vertx.elasticsearch.integration.GuiceIntegrationTest
Starting test: GuiceIntegrationTest#test1Index 
[Jarella] loaded [], sites [] 
[Jarella] failed to get node info for {#transport#-2}{180.168.41.175}{dockerhost/180.168.41.175:9300}, disconnecting... 
NodeDisconnectedException[[][dockerhost/180.168.41.175:9300][cluster:monitor/nodes/liveness] disconnected]

Starting test: GuiceIntegrationTest#test2Get 
[Two-Gun Kid] loaded [], sites [] 
Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2003 ms, time limit is 2000 
Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3006 ms, time limit is 2000 
Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 4010 ms, time limit is 2000

**Comment by minosniu** [comment]
Occasionally, test2Get would pass, but test3Search_Simple keeps on getting thread blocked exceptions...

Perhaps it's something on my local Elasticsearch? I started 2 instances, and made sure that the cluster status is GREEN.

**Comment by minosniu** [comment]
I was wrong. With your latest commit, all integration-tests passed. Thanks for the effort.
